### ISSUE TITLE
Interested in submitting to DefinitelyTyped?

### ISSUE THREAD

**Issue by hypexr** [swissspidy/typed-massive-js#1]

**Comment by swissspidy** [comment]
Hey there, thanks for asking!

I mainly created this for internal use as you might have seen that I added some custom properties. If there's interest, I'm happy to polish it up and submit it to DefinitelyTyped (together with some tests)

**Comment by hypexr** [comment]
Yeah, I'm definitely interested in having it there.  I like massivejs and it would be great to have the type definitions easily available.  

Thanks!

**Comment by swissspidy** [comment]
I created a PR for this on the DefinitelyTyped repository: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14745

I'm not using massive-js anymore, so I'm not sure the definitions are up-to-date. If not, feel free to fork my work on that PR and create one on your own.

**Comment by swissspidy** [comment]
The PR has been merged.
