### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by LiveLikeLastDay** [swissspidy/typed-massive-js#2]
Nice work, but could you have a README file to show us how to use it?

Thanks.

**Comment by swissspidy** [comment]
Hey there,

Thanks for submitting this issue. As per #1, I'm looking into submitting this to the DefinitelyTyped repository. Until then you can use `typings` (run `npm install -g typings` to install) to add this repository to your own project. Example:

``` bash
typings install github:swissspidy/typed-massive-js#c05efaf52d0f006a762d011bd38b56a89fe7587b
```

This will add the type definitions to your project's `typings.json` file. Here's an excerpt:

``` json
{
    "dependencies": {
        "massive": "github:swissspidy/typed-massive-js#c05efaf52d0f006a762d011bd38b56a89fe7587b"
    },
    "ambientDependencies": {}
}
```

Note: I don't guarantee that the type definitions are correct, as I made some custom edits specific for my own use case (see #1 again).

After submitting to DefinitelyTyped, you would be able to simply use `typings install massive`.

Let me know if it works.

**Comment by LiveLikeLastDay** [comment]
Thanks, it does help!

**Comment by swissspidy** [comment]
`typings install massive` should now work as it has been added to DefinitelyTyped.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14745
